// ============================================================
// RAPPORT (version texte simple - sans jsPDF pour éviter les crashs)
// ============================================================

import { useState } from 'react';
import { FileText } from 'lucide-react';
import { runBacktest90Days } from '@/services/backtest';

interface ReportPanelProps {
  signals: any[];
  currentPrice: number;
  macroScore: number;
  session: string;
  squeezeStatus: string;
}

export function ReportPanel({ signals, currentPrice, macroScore, session, squeezeStatus }: ReportPanelProps) {
  const [showReport, setShowReport] = useState(false);

  const confirmedCount = signals.filter(s => s.status === 'confirmed').length;
  const formingCount = signals.filter(s => s.status === 'forming').length;

  const generateTextReport = () => {
    const bt = runBacktest90Days();
    const now = new Date().toLocaleString('fr-FR');

    let report = `
====================================
XAU/USD ANALYSE PRO - RAPPORT
${now}
====================================

PRIX ACTUEL: $${currentPrice.toFixed(2)}
Session: ${session}
Macro Score: ${macroScore}/100
Squeeze: ${squeezeStatus}

--- SIGNAUX ---
Confirmes: ${confirmedCount}
Formation: ${formingCount}

`;

    signals.forEach((s, i) => {
      report += `
Signal #${i + 1} [${s.status?.toUpperCase() || 'N/A'}]
  Type: ${s.type || 'N/A'}
  Direction: ${s.direction || 'N/A'}
  Entry: $${(s.entryPrice || s.entry || 0).toFixed(2)}
  SL: $${(s.stopLoss || s.sl || 0).toFixed(2)}
  TP1: $${(s.takeProfit1 || s.tp1 || 0).toFixed(2)}
  RR: 1:${(s.riskReward || s.rr || 0).toFixed(1)}
  Confiance: ${s.confidence || 0}%
  Score: ${s.score || 0}/100
`;
    });

    report += `
--- BACKTEST 90 JOURS ---
Total Trades: ${bt.totalTrades}
Win Rate: ${bt.winRate}%
Gagnants: ${bt.winningTrades}
Perdants: ${bt.losingTrades}
R/R Moyen: 1:${bt.avgRR}
Profit Factor: ${bt.profitFactor}
Sharpe Ratio: ${bt.sharpeRatio}
Max Drawdown: ${bt.maxDrawdown}%

--- FILTRES ACTIFS ---
14 Filtres Qualite: OK
5 Filtres Avances: OK
  - Holy Trinity: Macro+H4+H1
  - Golden Window: 13h-16h GMT
  - Auto-Cut WR>65%
  - Diamond Score 115+
  - Smart ATR SL

====================================
Generated by XAU/USD 24/7 Analyzer
====================================
`;

    return report;
  };

  const downloadReport = () => {
    const report = generateTextReport();
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `XAUUSD_Rapport_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-[#1a202c] rounded-xl border border-[#2d3748] p-4">
      <h3 className="text-sm font-bold text-[#a0aec0] mb-3 flex items-center gap-2">
        <FileText className="w-4 h-4 text-[#63b3ed]" /> Rapport d&apos;Analyse
      </h3>

      <div className="space-y-2 mb-3 text-xs">
        <div className="flex justify-between">
          <span className="text-[#4a5568]">Prix</span>
          <span className="font-bold text-white">${currentPrice.toFixed(2)}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-[#4a5568]">Session</span>
          <span className="font-bold text-[#ffd700]">{session}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-[#4a5568]">Macro Score</span>
          <span className="font-bold text-[#63b3ed]">{macroScore}/100</span>
        </div>
        <div className="flex justify-between">
          <span className="text-[#4a5568]">Squeeze</span>
          <span className="font-bold text-[#a0aec0]">{squeezeStatus}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-[#4a5568]">Signaux confirmes</span>
          <span className="font-bold text-[#48bb78]">{confirmedCount}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-[#4a5568]">Signaux formation</span>
          <span className="font-bold text-[#ffd700]">{formingCount}</span>
        </div>
      </div>

      <button
        onClick={downloadReport}
        className="w-full px-4 py-2.5 bg-[#2962FF] text-white rounded-lg font-bold text-xs hover:bg-[#1a237e] transition-all"
      >
        Telecharger le Rapport (.txt)
      </button>

      <button
        onClick={() => setShowReport(!showReport)}
        className="w-full mt-2 px-4 py-2 bg-[#0d1117] border border-[#4a5568] text-[#a0aec0] rounded-lg font-bold text-xs hover:border-[#2962FF] transition-all"
      >
        {showReport ? 'Masquer' : 'Voir'} le rapport
      </button>

      {showReport && (
        <pre className="mt-3 p-3 bg-[#0d1117] rounded text-[10px] text-[#a0aec0] overflow-auto max-h-60 font-mono whitespace-pre-wrap">
          {generateTextReport()}
        </pre>
      )}
    </div>
  );
}
